---
version: '3.7'

services:
  opi-sessionoffload-client:
    container_name: opi-sessionoffload-client
    build:
      context: client
    networks:
      - internet
      - intranet
    depends_on:
      - opi-sessionoffload-server
    command: /opi-sessionoffload-client -addr=opi-sessionoffload-server:50151

  opi-sessionoffload-server:
    container_name: opi-sessionoffload-server
    build:
      context: .
      dockerfile: xdp/Dockerfile
    networks:
      - internet
      - intranet
    ulimits:
      memlock: 1073741824
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.rp_filter=0
    privileged: true
    command: /opt/xdp/start.sh

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
