name: robotframework-tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'sessionoffload/v2/**'
      - 'sessionoffload/Makefile'
      - 'tests/robot/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'sessionoffload/v2/**'
      - 'sessionoffload/Makefile'
      - 'tests/robot/**'
      - '.github/workflows/main.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-security-skip-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-protobuf:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No protobuf build required"'

  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No robot test run required"'
