name: robotframework-tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'protos/**'
      - 'tests/robot/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'protos/**'
      - 'tests/robot/**'
      - '.github/workflows/main.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-security-skip-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: tests/robot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No robot test run required"'
